AWSTemplateFormatVersion: 2010-09-09
Description: ---

Resources: 
  OnCreateLambda:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Tags:
      - Key: Stage
        Value: test
      TemplateURL: !Join ['', ['https://cloudformation-code-repo-flower-platform.s3.ap-northeast-2.amazonaws.com/', 'lambda/on_create_stack.yaml']]
      Parameters:
        CodeBucketName: cloudformation-code-repo-flower-platform
        ResourceBucketName: cloudformation-code-repo-flower-platform
        CodeKey: 'non-cfn/on_create_stack/on_create_stack.py.zip'
        LayerKey: 'non-cfn/on_create_stack/python.zip'
        SecGroupId: sg-0b05a014670a5734a
        SubnetIds: !Join [',', ['subnet-0978a65d3e968cddd', 'subnet-050588264810368ff']]

  OnCreateStack:
    Type: "Custom::OnCreateStack"
    Properties:
      ServiceToken: !GetAtt OnCreateLambda.Outputs.LambdaArn
      DB_ENDPOINT: test-env-database-1ovxafcat5zph-rds-hspnvz5kywfc.c3ftl6psdgtp.ap-northeast-2.rds.amazonaws.com
      BUCKET_NAME: cloudformation-code-repo-flower-platform
      DDL_KEY: 'non-cfn/database/ddl.sql'
      DML_KEY: 'non-cfn/database/dml.sql'
      USER: admin
      PASSWORD: helloWorld!

