AWSTemplateFormatVersion: 2010-09-09
Description: Create VPC for flower platform
Parameters:
  AZ:
    Description: AZ to use
    Type: String
    Default: ap-northeast-2a

  BucketUrl:
    Description: it is a bucket template Url.
    Type: String
    Default: "https://cloudformation-code-repo-flower-platform.ap-northeast-2.amazonaws.com/"


Resources: 
  VPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: '10.0.0.0/16'
      EnableDnsHostnames: true
      Tags:
      - Key: Stage
        Value: test
      - Key: Description
        Value: it is a VPC for test stage
  
  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
      - Key: Stage
        Value: test
      - Key: Description
        Value: it is a route table for test stage
    DependsOn: VPC

  VPCGatewayAttachment:
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties: 
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Tags:
      - Key: Stage
        Value: test
      TemplateURL: !Join ['', [!Ref BucketUrl, 'network/public_subnet.yaml']]
      Parameters:
        VpcId: !Ref VPC
        IgId: !GetAtt InternetGateway.InternetGatewayId
        AZ: !Ref AZ
        CidrBlock: 10.0.0.0/24