AWSTemplateFormatVersion: 2010-09-09
Description: template for creating lambda layer
Parameters:
  
  LayerBucketName:
    Description: Bucket name for layer
    Type: String
  LayerS3Key:
    Description: key name of layer zipped file
    Type: String
  

Resources: 
  LambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: !Sub ${AWS::StackName}-lambda-layer
      Description: Layer for all lambdas
      CompatibleRuntimes: 
        - python3.7
        - python3.8
      Content: 
        S3Bucket: !Ref LayerBucketName
        S3Key: !Ref LayerS3Key

Outputs:
  LambdaLayerArn:
    Description: ARN for lambda layer
    Value: !Ref LambdaLayer